---
- name: Apache install
  hosts: backend_servers
  tasks:
  - name: install apache-backend
    apt:
      name: apache2
      state: present
  - name: "run the script"
    shell: echo "<h1> Welcome  TO $(hostname -f)</h1>" > /var/www/html/index.html
    
  - name: "restart apache2"
    service:
      name: "apache2"
      state: started
